/**
 * IczTask API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Task } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TaskApiServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    apiTaskGet(extraHttpRequestParams?: any): Observable<Array<Task>>;

    /**
     * 
     * 
     * @param id 
     */
    apiTaskIdDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    apiTaskIdGet(id: number, extraHttpRequestParams?: any): Observable<Task>;

    /**
     * 
     * 
     * @param task 
     */
    apiTaskPost(task?: Task, extraHttpRequestParams?: any): Observable<Task>;

    /**
     * 
     * 
     * @param task 
     */
    apiTaskPut(task?: Task, extraHttpRequestParams?: any): Observable<Task>;

}
